---
swagger: '2.0'
info:
  version: 1.0.0
  title: DeepStyle
  description: Run DeepStyle (aka NeuralStyle) in the cloud 
  x-21-github-profile-url: https://github.com/tleyden
  x-21-github-project-url: https://github.com/tleyden/deepstyle-21-market
  x-21-quick-buy: 21 buy http://10.244.164.194:8001/buy --maxprice 275000 --data '{"style_image_url": "http://tleyden-misc.s3.amazonaws.com/21style/pollock_key.jpg", "content_image_url": "http://tleyden-misc.s3.amazonaws.com/21style/flowers.jpg"}'
  x-21-category: utilities
  x-21-keywords:
    - NeuralArt
    - StyleTransfer
    - DeepArt
    - DeepLearning
  x-21-app-image: "https://cdn.filepicker.io/api/file/5niwxYoNRUe7CiibzHaZ"
  x-21-total-price:
    min: 275000
    max: 275000
  contact:
    name: Traun Leyden
    email: traun.leyden@gmail.com
  license:
     name: Apache2 License
schemes:
  - http
basePath: /
host: 10.244.164.194:8001
x-21-manifest-path: /manifest
paths:
  /buy:
    post:
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: The style and content images specified via a URL OR raw base64 data
          required: true
          schema:
            $ref: "#/definitions/Buy"
      responses:
        200:
          description: OK
  /redeem/{token}/status:
    get:
      produces:
        - application/json
      parameters:
        - name: token
          in: path
          type: string
          description: The token returned from calling the buy endpoint
          required: true
      responses:
        200:
          description: The finished image is ready to be downloaded
        404:
          description: The image is still being processed
  /redeem/{token}/image:
    get:
      produces:
        - image/png
      parameters:
        - name: token
          in: path
          type: string
          description: The token returned from calling the buy endpoint
          required: true
      responses:
        200:
          description: The content of the finished image
definitions:
  Buy:
    type: object
    properties:
      style_image_url:
        type: string
        description: The URL of the style image to process.  For example, an image of a painting.  
      content_image_url:
        type: string
        description: The URL of the content image to process.  For example, a photo of you.
      style_image_base64_data:
        type: string
        description: The base64 data of the style image to process.  Use this instead of style_image_url, but not both.
      content_image_base64_data:
        type: string
        description: The base64 data of the content image to process.  Use this instead of content_image_url, but not both.

        

